name: clipboard
description: "CopyCat Clipboard: One Clipboard, Limitless Productivity"
publish_to: "none"
version: 2.0.0+76

environment:
  sdk: ">=3.11.0 <4.0.0"

isar_version: &isar_version 3.3.0-dev.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^2.7.1
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  freezed_annotation: ^2.4.4
  path: ^1.9.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  get_it: ^8.3.0
  go_router: ^17.2.3
  dartz: ^0.10.1
  form_validator: ^2.1.1
  window_manager: ^0.5.1
  timeago: ^3.7.1
  isar_community: *isar_version
  isar_community_flutter_libs: *isar_version
  uuid: ^4.5.3
  rxdart: ^0.28.0
  internet_connection_checker_plus: ^3.0.0
  url_launcher: ^6.3.2
  googleapis: ^16.0.0
  file_picker: ^11.0.2
  http: ^1.6.0
  blurhash_dart: ^1.2.1
  mime: ^2.0.0
  image: ^4.8.0
  intl: ^0.20.2
  app_links: ^7.0.0
  device_preview: ^1.2.0
  async: ^2.13.1
  win32_registry: ^2.1.0
  share_handler: ^0.0.25
  universal_io: ^2.3.1
  duration: ^4.0.3
  open_filex: ^4.7.0
  hotkey_manager: ^0.2.3
  focus_window:
    path: packages/focus_window
  quick_paste_popup:
    path: packages/quick_paste_popup
  package_info_plus: ^8.3.1
  tray_manager: ^0.5.2
  flutter_platform_alert: ^0.8.0
  device_preview_screenshot: ^1.0.0
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  upgrader: 13.1.0
  in_app_review: ^2.0.9
  retry: ^3.1.2
  launch_at_startup: ^0.5.1
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.2.4
  screen_retriever: ^0.2.0
  no_screenshot: ^1.1.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^3.0.1
  flutter_svg_provider:
    git:
      url: https://github.com/raj457036/flutter_svg_provider.git
  android_background_clipboard:
    path: packages/android_background_clipboard
  animate_do: ^5.1.0
  installed_apps:
    git:
      url: https://github.com/raj457036/installed_apps.git
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  video_player: ^2.10.0
  emoji_picker_flutter:
    git:
      url: https://github.com/raj457036/emoji_picker_flutter.git
  purchases_flutter: ^10.1.0
  purchases_ui_flutter: ^10.1.0
  supabase_flutter: ^2.12.4
  supabase_auth_ui: ^0.5.5
  super_clipboard: ^0.9.1
  super_drag_and_drop: ^0.9.1
  easy_worker: ^1.2.3
  cacherine: ^1.1.4
  clipboard_watcher: ^0.3.0
  crypto: ^3.0.7
  mdns_dart: ^2.2.1
  ntp: ^2.0.0
  nanoid2: ^2.0.1
  tiny_storage: ^2.0.2
  share_plus: ^10.1.4
  device_info_plus: ^11.5.0
  equatable: ^2.0.8
  any_link_preview: ^3.0.3
  cached_network_svg_image: ^2.0.0
  cached_network_image: ^3.4.1
  synchronized: ^3.4.0
  archive: ^4.0.9
  statsfl: ^2.3.0
  open_dir: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  isar_community_generator: *isar_version
  freezed: ^2.5.8
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4
dependency_overrides:
  connectivity_plus: 7.0.0
  supabase_auth_ui:
    path: packages/supabase_auth_ui
  # irondash_engine_context:
  #   git:
  #     url: https://github.com/Sabbar-Engineering/irondash
  #     path: "engine_context/dart"

flutter:
  config:
    enable-swift-package-manager: false
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - fonts/

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: fonts/RobotoFlex-VariableFont.ttf
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
    - family: DockIcons
      fonts:
        - asset: fonts/DockIcons.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

flutter_launcher_icons:
  image_path: "./resources/icon_2026_flat.png"
  android: true
  adaptive_icon_background: "#262141"
  adaptive_icon_foreground: "./resources/icon_2026_adaptive_fg.png"
  adaptive_icon_monochrome: "./resources/icon_2026_monochrome_fg.png"
  min_sdk_android: 24

  ios: "./resources/icon_2026_ios.png"
  image_path_ios_dark_transparent: "./resources/icon_2026_rounded.png"
  remove_alpha_ios: true
  desaturate_tinted_to_grayscale_ios: true
  background_color_ios: "#262141"

  windows:
    generate: true
    icon_size: 256
    image_path: "./resources/icon_2026_flat.png"

  macos:
    generate: true
    image_path: "./resources/icon_2026_macos.png"
