# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  private_lane :prepare_ios_dependencies do
    ios_dir = File.expand_path("..", __dir__)
    ruby_env = "env -u GEM_HOME -u GEM_PATH -u BUNDLE_GEMFILE -u BUNDLE_BIN_PATH"

    sh "flutter clean"
    sh "flutter pub get"
    sh "cd '#{ios_dir}' && #{ruby_env} pod install"
  end

  desc "Runs all the tests"
  lane :test do
    sh "flutter test"
  end

  # MARK: - Deployment lanes
  desc "Build and upload to TestFlight"
  lane :beta_testers do
    prepare_ios_dependencies

    sh "env -u GEM_HOME -u GEM_PATH -u BUNDLE_GEMFILE -u BUNDLE_BIN_PATH flutter build ipa \
      --release \
      --dart-define-from-file=local/prod.json \
      --obfuscate \
      --split-debug-info=build_symbols"

    ipa_path = Dir["../build/ios/ipa/*.ipa"].max_by { |f| File.mtime(f) }

    if ipa_path.nil?
      UI.user_error!("No IPA found in ../build/ios/ipa")
    end

    upload_to_testflight(
      ipa: ipa_path,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and upload for App Store review"
  lane :release do
    prepare_ios_dependencies
    sh "env -u GEM_HOME -u GEM_PATH -u BUNDLE_GEMFILE -u BUNDLE_BIN_PATH flutter build ios --config-only --release --dart-define-from-file=local/prod.json --obfuscate --split-debug-info=./build_symbols"
    sh "env -u GEM_HOME -u GEM_PATH -u BUNDLE_GEMFILE -u BUNDLE_BIN_PATH flutter build ipa \
      --release \
      --dart-define-from-file=local/prod.json \
      --obfuscate \
      --split-debug-info=build_symbols"

    ipa_path = Dir["../build/ios/ipa/*.ipa"].max_by { |f| File.mtime(f) }

    if ipa_path.nil?
      UI.user_error!("No IPA found in ../build/ios/ipa")
    end

    upload_to_app_store(
      ipa: ipa_path,
      submit_for_review: false,
      automatic_release: false,
      skip_screenshots: true,
      skip_metadata: true,
      skip_app_version_update: true
    )
  end
end
